version: '3.8'

services:
  playwright-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orangehrm-tests
    volumes:
      # Mount reports and screenshots to host machine
      - ./reports:/app/reports
      - ./screenshots:/app/screenshots
    env_file:
      - .env
    networks:
      - test-network

networks:
  test-network:
    driver: bridge